version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: creditscore-container
    environment:
      POSTGRES_DB: creditscore-db
      POSTGRES_USER: hilman
      POSTGRES_PASSWORD: hilman123
    volumes:
      - postgres_data:/var/lib/postgresql/18/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: creditscore-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin894627
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
